import mongoose from "mongoose";

const MemberSchema = new mongoose.Schema(
    {
        // ID will be auto-generated by MongoDB (_id), but we might want to map existing IDs if migrating
        firstName: { type: String, required: true },
        lastName: { type: String },
        email: { type: String, unique: true },
        phone: { type: String },
        gender: { type: String, enum: ["male", "female", "other"] },
        joinDate: { type: String, required: true }, // Keeping as String ISO for simplicity to match frontend types
        photoBase64: { type: String },
        planId: { type: String },
        notes: { type: String },
        gymId: { type: mongoose.Schema.Types.ObjectId, ref: "Gym", required: true },
    },
    { timestamps: true }
);

// Add a transform to change _id to id
MemberSchema.set("toJSON", {
    virtuals: true,
    versionKey: false,
    transform: function (doc, ret: any) {
        ret.id = doc._id.toString();
        delete ret._id;
    },
});

export default mongoose.models.Member || mongoose.model("Member", MemberSchema);
