import mongoose from "mongoose";

const MemberSchema = new mongoose.Schema(
    {
        // ID will be auto-generated by MongoDB (_id), but we might want to map existing IDs if migrating
        firstName: { type: String, required: true },
        lastName: { type: String },
        email: { type: String, unique: true, sparse: true },
        phone: { type: String },
        gender: { type: String, enum: ["male", "female", "other"] },
        joinDate: { type: String, required: true }, // Keeping as String ISO for simplicity to match frontend types
        photoBase64: { type: String },
        planId: { type: String },
        notes: { type: String },
        gymId: { type: mongoose.Schema.Types.ObjectId, ref: "Gym", required: true },
        // Assigned Trainer
        trainerId: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
        // Multi-branch support - optional for backward compatibility
        branchId: { type: mongoose.Schema.Types.ObjectId },
        // Soft delete support
        deletedAt: { type: Date, default: null },

        // Member Portal Login Support
        portalPassword: { type: String, select: false }, // Hashed password for portal login
        portalPin: { type: String, select: false }, // 4-6 digit PIN alternative
        portalEnabled: { type: Boolean, default: false },
        lastPortalLogin: { type: Date },

        // QR Code for check-in
        qrCode: { type: String }, // Unique QR identifier

        // Attendance tracking
        attendanceStreak: { type: Number, default: 0 },
        lastCheckIn: { type: Date },
        totalCheckIns: { type: Number, default: 0 },
    },
    { timestamps: true }
);

// Indexes
MemberSchema.index({ gymId: 1, email: 1 });
MemberSchema.index({ gymId: 1, branchId: 1 });
MemberSchema.index({ gymId: 1, qrCode: 1 });
MemberSchema.index({ gymId: 1, trainerId: 1 });
MemberSchema.index({ gymId: 1, phone: 1 });
MemberSchema.index({ gymId: 1, deletedAt: 1 });
MemberSchema.index({ gymId: 1, firstName: 1, lastName: 1 });

// Add a transform to change _id to id
MemberSchema.set("toJSON", {
    virtuals: true,
    versionKey: false,
    transform: function (doc, ret: any) {
        ret.id = doc._id.toString();
        delete ret._id;
        // Never expose password/pin in JSON
        delete ret.portalPassword;
        delete ret.portalPin;
    },
});

export default mongoose.models.Member || mongoose.model("Member", MemberSchema);

